model:
  model_name: "llama-7b"
  vocab_size: 50257
  hidden_size: 128
  intermediate_size: 256
  num_hidden_layers: 2
  num_attention_heads: 4
  num_key_value_heads: 4
  max_position_embeddings: 128
  rms_norm_eps: 0.000001
  rope_theta: 10000.0
  attention_dropout: 0.0

training:
  batch_size: 1          # Keep small
  learning_rate: 0.0001
  num_epochs: 1
  max_seq_length: 64
  warmup_steps: 10
  weight_decay: 0.01
  gradient_clipping: 1.0

galore:
  rank: 16
  update_proj_gap: 5
  scale: 0.25
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]

federated:
  num_clients: 3
  num_rounds: 5          # ← INCREASE rounds since it's working!
  client_fraction: 1.0
  local_epochs: 1
  server_address: "localhost"
  server_port: 8080

kd:
  temperature: 3.0
  alpha: 0.5
